version: "3.3"

services:
  web:
    build: .
    ports:
      - 8080:8080
    environment:
        PORT: 8080
        GO111MODULE: "on"
        REDIS_URL:
        POSTGRES_URL:
        POSTGRES_DB:
        POSTGRES_USER:
        POSTGRES_PASSWORD:
        WEATHER_API_KEY: ""
  redis:
    image: redis:alpine

  db:
    image: postgres
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - 5432:5432
    volumes:
      - ./sql/create.sql:/docker-entrypoint-initdb.d/create.sql
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql